@echo off
echo Initializing Git...
git init
echo Adding files...
git add .
echo Committing...
git commit -m "Initial commit to main branch"
echo Setting branch to main...
git branch -M main
echo Adding remote...
git remote add origin https://github.com/mustafaezzy/MahalCare.git
git remote set-url origin https://github.com/mustafaezzy/MahalCare.git
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
